-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Dec 19, 2023 at 03:03 AM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.0.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `batikpedia`
--
CREATE DATABASE IF NOT EXISTS `batikpedia` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `batikpedia`;

-- --------------------------------------------------------

--
-- Table structure for table `artikel_batik`
--

DROP TABLE IF EXISTS `artikel_batik`;
CREATE TABLE `artikel_batik` (
  `id_artikel` int(10) NOT NULL,
  `nama_batik` varchar(255) NOT NULL,
  `judul` varchar(255) NOT NULL,
  `isi` text NOT NULL,
  `url_artikel` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Truncate table before insert `artikel_batik`
--

TRUNCATE TABLE `artikel_batik`;
--
-- Dumping data for table `artikel_batik`
--

INSERT INTO `artikel_batik` (`id_artikel`, `nama_batik`, `judul`, `isi`, `url_artikel`) VALUES
(1, 'Batik Bali', 'Batik Bali Merak Abyorhokokai: Wujud Nyata Keindahan Pulau Dewata', 'Batik menjadi salah satu karya seni Indonesia yang cukup populer sampai ke luar negeri. Selain unik, batik juga memiliki makna khusus tergantung dari motif-motifnya.\\nBahkan di setiap daerah di Indonesia, memiliki ciri khas batik masing-masing. Mulai dari Batik Solo, Batik Madura, Batik Pekalongan hingga Batik Bali.\\nSemuanya memiliki makna yang menarik. Seperti Batik Bali Merak Abyorhokokai, batik ini salah satu batik yang dimiliki oleh Pulau Bali.\\nMelansir dari laman Budaya Indonesia, motif batik Bali Merak Abyorhokokai menggambarkan keindahan Burung Merak sebagai poros corak utama pada kain.\\nKelopak yang tersusun rapi menjadi sayap merak ini menyerupai Bunga Sakura. Merak Abyorhokokai sendiri dipengaruhi oleh kebudayaan Jepang, sehingga tak heran jika dalam batik ini tersusun rapi Bunga Sakura.\\nMerak Abyorhokokai mampu menginterpretasikan bagaimana keindahan Pulau Dewata Bali dengan merak sebagai simbol utama.\\nWarna dari Batik Merak Abyorhokokai ini tidak terlalu mencolok, sehingga cocok digunakan untuk siapa saja, baik anak muda maupun orang tua.\\nBatik biasanya didominasi dengan warna coklat sehingga terkesan gelap dan tua. Berbeda dengan Batik Merak Abyorhokokai ini, warnanya kalem, yaitu perpaduan warna merah muda, kuning dan biru untuk Bunga Sakuranya.\\nKemudian badan merak didominasi dengan warna kuning yang tidak terlalu mencolok. Sementara itu backgroundnya berwarna gelap, sehingga kesan gambar merak dan Bunga Sakura ini terlihat jelas.\\nBatik Merak Abyorhokokai ini menggambarkan semangat Bali sebagai Pulau Dewata. Sesuai dengan keindahannya yang ditampilkan, harga dari Batik ini tergolong sedikit mahal, yaitu berkisar antara Rp 500 Ribu – Rp 1 Juta.', 'https://bali.suara.com/read/2023/11/08/171000/batik-bali-merak-abyorhokokai-wujud-nyata-keindahan-pulau-dewata'),
(5, 'Batik Ceplok', 'Mengenal Batik Ceplok, dari Asalnya hingga Variasi Motifnya', 'Motif batik ceplok adalah salah satu jenis batik kuno yang berasal dari Yogyakarta. Batik ini memiliki unsur simetris dan membentuk sudut empat arah. Motif batik ceplok dikenal juga dengan sebutan batik ceplokan, yang mana jenis batik ini ada sejak jaman Kerajaan Mataram yaitu berpusat di Kotagede.\\nBatik ceplokan pernah tercatat dalam kesenian batik Indonesia, yaitu sebagai ragam hias tertua. Motif batik satu ini kental akan corak khas Jawa. Mau tahu info lebih banyak mengenai motif batik ceplok? Simak kelanjutannya ya.\\nCeplokan atau motif batik ceplok, merupakan satu kata dari Bahasa Jawa yaitu ceplok yang memiliki arti sekuntum. Kata ini digunakan untuk menjelaskan model hiasan batik yang berupa satuan demi satuan.\\nKatanya, motif ini terinspirasi dari hiasan candi terutama pada dinding candi yang bercorak Hindu dan Buddha dengan motifnya yang sakral dan mendalam.\\nDikutip dari rumahbatikbedjo.com menyebutkan bahwa secara artistik motif batik ceplokan ini menggambarkan keteraturan dan keseimbangan yang penting untuk menjalankan kehidupan. Hiasannya yang berulang dalam jumlah yang banyak mengartikan sebagai suatu kumpulan. Dalam filosofi Jawa, ini dinamakan grampol yang berarti berkumpulnya segala hal yang baik.\\nDapat diartikan bahwa motif batik ceplok ini merupakan bersatunya senilai kehidupan yang baik mulai dari keteraturan, keserasian, hingga kebijaksanaan. Nah, meski tampak simple ternyata semua motif batik itu memiliki maknanya tersendiri loh Kawan!\\nSeperti yang telah dijelaskan di awal, bahwa motif batik ceplok berasal dari Yogyakarta. Dipercaya bahwa motif batik ceplok ada sejak jaman kerajaan Mataram, sehingga termasuk karya seni batik kuno.\\nPada saat itu, penggunaan jenis batik ceplok cukup terbatas, hanya orang-orang tertentu saja yang boleh mengenakannya seerti pegawai di lingkungan Kerajaan.', 'https://www.goodnewsfromindonesia.id/2023/09/23/mengenal-batik-ceplok-dari-asalnya-hingga-variasi-motifnya'),
(8, 'Batik Garutan', 'Eksistensi Batik Garutan di Tengah Gempuran Produk China', 'Dari banyak daerah penghasil kain batik di tanah air, Garut menjadi salah satu yang terbaik. Batik Garutan, bahkan diperjualbelikan di seantero negeri, hingga ke mancanegara.\\nSama halnya dengan berbagai daerah di Indonesia, Garut juga memiliki batiknya sendiri. Batik yang berasal dari kota asal Jawa Barat berjuluk Swiss van Java ini, disebut batik Garut, atau batik Garutan.\\nDikutip dari sebuah jurnal karya Desi Qoriah berjudul Industri Batik Garutan di Era Milenial (Studi Kasus Batik Garutan di Kabupaten Garut Jawa Barat) yang dipublish journal.uniga.ac.id, batik Garut memiliki keunikan.\\nYang menjadi ciri khasnya, adalah corak. Ada beragam corak yang menjadi ciri khas batik Garutan. Di antaranya adalah motif bilik. \"Motif Rereng Pacul, Rereng Peuteuy, Rereng Kembang Corong, Rereng Merak Ngibing, Cupat Manggu, Bilik dan Sapu Jagat,\" ucap Desi dalam jurnal tersebut.\\nDengan keberagaman motif yang dimiliki, membuat batik Garutan sangat bernilai ekonomis. Namun, berdasarkan penelitian yang dilakukan Desi, saat ini, para perajin lokal justru merana gara-gara munculnya batik printing asal China. Alasannya, karena batik printing asal China lebih murah dan masif di pasaran.\\n\"Batik printing dari China lebih murah,\" katanya.\\nLantas, bagaimana sebenarnya kondisi para perajin batik Garutan saat ini? Sabtu (1/10/2022) siang, detikJabar berkesempatan untuk berbincang dengan Ruda Pratama, pemilik salah satu produsen batik Garutan terkemuka di Garut, Viera Batik.\\nRuda mengungkapkan saat ini batik Garutan yang diproduksinya terus bersaing dengan batik-batik asal daerah lain di pasaran lokal.\\n\"Batik Garut terus berkembang dan dikenal lebih luas. Dari kekhasan motif, hingga warna yang terus mengikuti perkembangan fesyen yang menjadikan batik Garut sebagai pilihan bagi pecinta wastra Indonesia,\" kata Ruda di toko batik miliknya, Jalan Otista, Kecamatan Tarogong Kidul.\\nAda dua varian batik Garutan yang diminati di pasaran, berdasarkan teknik pembuatannya. Yakni batik tulis, serta batik cap. Batik tulis adalah yang paling istimewa. Sebab, pembuatannya memakan waktu. Maka tak heran jika harganya relatif lebih mahal dibanding batik cap. \\n\"Pembuatan batik jenis ini memakan waktu kurang lebih 1 sampai 2 bulan,\" katanya.\\nRuda mengaku tak khawatir dengan gempuran produk batik printing asal luar negeri, yang kini marak di pasaran. Sebab, batik Garutan memiliki kekhasan tersendiri yang sangat diminati di pasaran. Hanya satu yang menjadi kendala saat ini. Yaitu, mulai berkurangnya generasi pembuat batik.\\n\"Generasi perajin yang berkurang. Bahan baku juga cukup sulit,\" katanya.', 'https://www.detik.com/jabar/budaya/d-6324431/eksistensi-batik-garutan-di-tengah-gempuran-produk-china'),
(11, 'Batik Insang', 'Kain batik corak insang laris terjual menjelang HUT ke-252 Kota Pontianak', '\"Pontianak (ANTARA) - Kain batik corak insang laris terjual dan banyak dicari oleh masyarakat menjelang HUT ke-252 Kota Pontianak.\\n\"\"Batik corak insang ada dua jenis yaitu kain tenun biasa dan benang emas,\"\" kata Siti Aminah penjual kain saat ditemui di Pontianak, Sabtu (21/10).\\nKain tenun corak insang yang paling diminati oleh masyarakat ialah kain tenun benang emas yang dijual dengan harga Rp95.000. Sedangkan kain corak insang biasa dijual dengan harga Rp85.000.\\n\"\"Corak insang juga sering dipakai saat acara pernikahan,\"\" ujarnya.\\nIa menambahkan perkembangan penjualan kain batik corak insang dari tahun ke tahun terus meningkat dan makin banyak diminati oleh masyarakat di Kalbar terutama di Kota Pontianak.\\n\"\"Kain corak insang merupakan hasil tenun tradisional masyarakat Pontianak khususnya masyarakat Melayu,\"\" ungkapnya.\\nIa menjelaskan, kain dengan motif corak insang masih dikenakan oleh sebagian masyarakat Kota Pontianak, baik itu orang tua, anak-anak maupun remaja. Bahkan, beberapa desainer di Pontianak mulai mengkombinasikan corak insang dalam busana rancangannya.\\n\"\"Corak insang ini juga mempunyai beragam motif yang unik seperti Insang Berantai, Insang Delima, Insang Berombak, dan Insang Awan,\"\" katanya menjelaskan./nCorak insang sudah dikenal sejak masa Kesultanan Kadriah di bawah kekuasaan Sultan Syarif Abdurrahman Al Qadrie tahun 1771 hingga saat ini. Umumnya digunakan sebagai kelengkapan pakaian adat, salah satunya adalah dalam acara pernikahan. \\n\"\"Generasi muda harus selalu menjaga dan melestarikan budaya batik yang menjadi ciri khas bangsa,\"\" kata pedagang kain tersebut.\r\n\"', 'https://kalbar.antaranews.com/berita/553050/kain-batik-corak-insang-laris-terjual-menjelang-hut-ke-252-kota-pontianak'),
(13, 'Batik Lasem', 'Kain Batik Lasem Jadi Cendera Mata di KTT G20 Bali', 'Batik tulis Lasem bakal menjadii cendera mata atau barang kenang-kenangan di perhelatan internasional Presidensi G20. Kain batik tulis khas Lasem itu nantinya berupa syal atau selendang.\\nHal itu diungkapkan oleh salah satu perajin Batik Tulis Lasem, Santoso Hartono saat ditemui detikJateng, pada Kamis (22/9/2022) siang.\\n\"Asal mulanya itu kerja sama dengan Program Studi Desain Mode Universitas Kristen Maranatha dan APR (Asia Pacific Rayon) dalam kegiatan riset yang diadakan Mitras DUDI Kemendikbud RI. Membuat batik untuk syal, untuk cendera mata menteri-menteri yang datang di G20,\" terang Santoso.\\nSantoso mengatakan, motif dari kain batik tulis Lasem yang akan digunakan sebagai cendera mata di perhelatan G20, sudah ditentukan. Yakni motif latohan dan kricak. Bahkan metode pewarnaannya sendiri menggunakan teknik tradisional, memakai bahan pewarna yang alami, sehingga ramah lingkungan.\\n\"Sudah ditentukan, motifnya ada kricak, latohan. Pakainya warna alam. Dari bahan -bahan alami, dari daun kayu-kayuan. Jadi ramah lingkungan,\" Santoso menjelaskan.\\nPenggunaan warna dari bahan-bahan alami, menurut Santoso memiliki beberapa kelebihan. Misalnya seperti warna yang dihasilkan pada kain lebih terkesan kalem. Selain itu proses pembatikannya dinilai tidak mencemari lingkungan.\\n\"Keunggulannya warnanya lebih soft dan tidak mencemari lingkungan,\" tandas Santoso.\\nSantoso mengaku mendapat pesanan 100 helai kain batik Lasem untuk kegiatan Presidensi G2. Namun, hingga sejauh ini baru pihaknya kirim 60 helai.\\n\"Sementara baru 100 buah. Sudah dua kali pengiriman. Tiga puluh, tiga puluh,\" imbuh Santoso./nSatu helai kain batik tulis Lasem, Santoso mengatakan, proses pembuatannya membutuhkan waktu selama lebih dari sepekan. Mulai dari proses awal menggambar pola, hingga pewarnaan./n\"Satu kain bisa sampai satu minggu proses pembatikannya. Dari gambar pola dan ditambah sekitar lima hari untuk pewarnaan. Yang lama pewarnaannya, karena pakai bahan alami. Jadi harus berulang untuk mendapatkan warna yang maksimal,\" pungkas Santoso.', 'https://www.detik.com/jateng/bisnis/d-6306851/kain-batik-lasem-jadi-cendera-mata-di-ktt-g20-bali'),
(20, 'Batik Keraton', 'Kain Sang Raja, Batik-Batik Keraton Yogya yang Sarat Makna dan Filosofi', 'Setelah terakhir kali dilaksanakan pada 2019, Taman Pintar Yogyakarta kembali menggelar pameran batik ke-3 bertajuk \'Adiwastra Narawita: Kain Indah Sang Raja\'. Berbagai koleksi kain batik ditampilkan di Dome Area Gedung Oval Taman Pintar pada 28 Oktober hingga 3 November 2022.\\nPameran ini digelar dalam rangka memperingati Hari Batik Nasional pada 2 Oktober 2022 lalu sekaligus untuk mempertahankan pengakuan batik sebagai warisan kemanusiaan untuk budaya lisan dan non bendawi oleh UNESCO. Pameran ini menampilkan sebanyak 27 koleksi kain batik Keraton Yogya dan Kadipaten Pakualaman.\\nDalam tema kali ini, keindahan yang dimaksud tidak hanya semata-mata dari tampilan motif batik. Lebih dari itu, keindahan juga merupakan hasil manifestasi dari nilai-nilai spiritual dan pemurnian diri serta manusia dalam konteks harmoni dengan semesta alam yang tertib, serasi, dan seimbang. \\nKeraton Yogyakarta akan menampilkan koleksi batik Awisan Ndalem atau Batik Larangan. Batik Larangan merupakan motif-motif batik yang penggunaannya terikat dengan aturan-aturan tertentu di Keraton Yogyakarta dan tidak semua orang boleh memakainya.\\nBatik Larangan dilatarbelakangi oleh keyakinan adanya kekuatan spiritual maupun makna filsafat yang terkandung dalam motif kain batik. Motif pada kain batik dipercaya mampu menciptakan suasana yang religius serta memancarkan aura magis sesuai dengan makna yang dikandungnya. \\nOleh karenanya, beberapa motif kain batik, terutama yang mempunyai nilai falsafah tinggi, dinyatakan sebagai Batik Larangan. Sementara, Puro Pakualaman menampilkan kain batik bertema Dhaup Ageng Pakualaman: Kemilau Sang Surya Mulyarja.\\nKain batik tersebut merupakan bagian dari batik seri Asthabrata koleksi Kadipaten Pakualaman. Motif tersebut tercipta berdasarkan iluminasi tentang Batara Surya dalam naskah Sestradisuhul dan Sestra Ageng Adidarma.\\nSelain memamerkan kain batik, akan ada kegiatan yang dapat diikuti pengunjung, seperti membatik, mewiru, serta menulis nama menggunakan aksara jawa. Diharapkan, pengunjung dapat memperoleh pengetahuan baru tentang makna motif batik keraton atau kerajaan yang memiliki nilai filosofis tinggi.\\nAdapun pembukaan pameran dilaksanakan di Phytagoras Hall Taman Pintar pada Jumat (28/10/2022) lalu. Pembukaan tersebut dihadiri Gusti Kanjeng Ratu Bendara dan G.K.B.R.A.A Paku Alam (Gusti Putri).', 'https://www.liputan6.com/regional/read/5111062/kain-sang-raja-batik-batik-keraton-yogya-yang-sarat-makna-dan-filosofi');

-- --------------------------------------------------------

--
-- Table structure for table `data_batik`
--

DROP TABLE IF EXISTS `data_batik`;
CREATE TABLE `data_batik` (
  `id_batik` int(10) NOT NULL,
  `nama_batik` varchar(255) NOT NULL,
  `asal_batik` varchar(255) NOT NULL,
  `makna_batik` text NOT NULL,
  `url_gambar` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Truncate table before insert `data_batik`
--

TRUNCATE TABLE `data_batik`;
--
-- Dumping data for table `data_batik`
--

INSERT INTO `data_batik` (`id_batik`, `nama_batik`, `asal_batik`, `makna_batik`, `url_gambar`) VALUES
(1, 'Batik Bali', 'Bali', 'Batik Bali merupakan hasil penyebaran batik dari pulau Jawa. Bali memiliki potensi besar untuk pertumbuhan dan perkembangan kain batik, karena masyarakat Bali dikenal luas dengan kecerdasan tinggi dalam keterampilan artistiknya. Batik Bali dibuat untuk berbagai keperluan seperti upacara adat keagamaan dan kehidupan sehari-hari secara umum, serta memenuhi kebutuhan wisatawan sebagai oleh-oleh.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_bali.jpg'),
(2, 'Batik Betawi', 'Jakarta', 'Batik Betawi memiliki keunikan dibanding batik khas daerah lain. Keunikan yang ada terdapat pada warnanya yang mencolok, begitu juga dengan motifnya. Motif batik lebih terfokus pada kesenian budaya Betawi yang dipengaruhi oleh budaya Arab, India, Belanda, dan Cina. Dilihat dari motifnya, batik betawi terbagi dari beberapa jenis, yaitu Ondel-ondel, Nusa kelapa, Ciliwung, Rasamala, dan Salakanegara. Dari namanya, ternyata motif batik Betawi memiliki asal usul tersendiri.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_betawi.jpg'),
(3, 'Batik Ikat Celup', 'Jawa', 'Batik ikat celup adalah salah satu jenis batik yang dibuat dengan teknik ikat celup. Teknik ini adalah teknik mewarnai kain dengan cara mengikat kain dengan cara tertentu sebelum dilakukan pencelupan.\n\nSejarah batik ikat celup diperkirakan berasal dari Tiongkok, yang kemudian menyebar ke India dan wilayah-wilayah di nusantara. Beberapa peninggalan menunjukkan bahwa teknik ikat celup telah digunakan pada masa Dinasti T\'ang pada abad ke-6.\n\nDi Indonesia, batik ikat celup dikenal dengan berbagai nama, seperti jumputan (Palembang), tritik atau jumputan (Jawa), serta sasirangan (Banjarmasin).', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_celup.jpg'),
(4, 'Batik Cendrawasih', 'Papua', 'Burung Cendrawasih merupakan motif yang menggambarkan burung endemik di tanah Papua. Cendrawasih adalah salah satu spesies burung langka, dilindungi oleh pemerintah Indonesia. Burung ini dipercaya sebagai burung surga yang menghubungkan kehidupan di bumi dengan surga. Motif ini juga dianggap sebagai motif sakral dan mewakili identitas masyarakat Papua, baik di provinsi Papua maupun Papua Barat.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_cendrawasih.jpg'),
(5, 'Batik Ceplok', 'Yogyakarta', 'Batik ceplok atau ceplokan merupakan jenis batik yang memiliki pola atau motif dengan bentuk dasar geometri, seperti persegi, oval maupun bintang yang disusun melingkar sehingga menyerupai sekuntum bunga dengan pola simetris. Bentuk tersebut terinsirasi dari buah kawung atau buah aren yang dibelah empat.\nVariasi dalam batik ceplok sangat kaya, bentuk utama geometris bisa diisi atau dalam istilah batik disebut isen-isen dengan motif batik lainya seperti kawung, parang klithik, truntum atau hiasan isen-isen lainnya seperti bunga dan gerdo atau garuda.Motif batik ceplok ini menggambarkan suratan takdir dan keteraturan kehidupan, bawah dalam kehidupan di dunia sudah ada aturan dan garisnya. Sehingga dharapkan sipemakai batik ini dapat menjalani hidup secara teratur. Pada zaman dulu, batik ceplok digunakan oleh aparat pemerintahan. Dengan menggunakan motif batik ini diharapan para aparat pemerintahan akan bertugas dengan benar dan jujur.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_ceplok.jpg'),
(6, 'Batik Ciamis', 'Ciamis, Jawa Barat', 'Batik Ciamis sangat berbeda dengan jenis batik dari wilayah lain, yaitu corak batiknya tidak telalu rumit dan berkarakter sederhana. Motif batik Ciamis seringkali disebut juga dengan batik Ciamisan yang merepresentasikan keindahan alam kota Ciamis, maka kita tidak heran jika motif batik ciamisan banyak memunculkan motif rereng atau lereng atau tebing miring (motif yang terbentuk sekilas seperti motif parang batik jawa).', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_ceplok.jpg'),
(7, 'Batik Dayak', 'Kalimantan', 'Kisah Putri Junjung Buih yang meminta kain tenun dan kain calap dalam satu hari kepada Patih Lambung Mangkurat menjadi awal mula perkembangan motif batik Kalimantan. Motif batik Dayak pun menjadi bagian dari budaya masyarakat lokal, khususnya suku Dayak. Batik Dayak memiliki makna keberanian dan harmonisasi kebudayaan.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_dayak.jpg'),
(8, 'Batik Garutan', 'Garut, Jawa Barat', 'Batik Garut berasal dari warisan nenek moyang yang berlangsung secara turun-temurun dan telah berkembang cukup lama sebelum masa kemerdekaan Indonesia. Hingga tahun 1945, batik Garut semakin populer dengan sebutan batik tulis Garutan yang mengalami masa kejayaan antara tahun 1967 sampai 1985. Batik Garutan umumnya digunakan untuk kain sinjang, tapi berfungsi juga untuk memenuhi kebutuhan sandang dan lainnya. Bentuk motif Batik Garut merupakan cerminan dari kehidupan sosial budaya, falsafah hidup, dan adat istiadat orang Sunda. Motif-motif Batik Garut dihadirkan berbentuk geometrik sebagai ciri khas ragam hiasnya, selain itu juga bermotif flora dan fauna. Bentuk geometrik umumnya mengarah ke garis diagonal dan bentuk kawung atau belah ketupat. Untuk warna, Batik Garutan didominasi oleh warna krem yang dipadukann dengan warna-warna cerah lainnya yang merupakan karakteristik khas Batik Garutan.Saat ini pengolahan Batik Garutan terkonsentrasi di Kota Garut, Jawa Barat.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_garutan.jpg'),
(9, 'Batik Gentongan', 'Madura, Jawa Timur', 'Batik Gentongan tercipta karena budaya di wilayah pesisir. Di mana ketika para suami bekerja sebagai nelayan, para istri akan membatik sembari menunggu kepulangan suaminya selama berbulan-bulan. Pada saat itu batik tidak digunakan sebagai mata pencaharian masyarakat setempat, melainkan sebagai hadiah yang akan diberikan kepada suami untuk menyambut kepulangannya. Batik Gentongan diberikan kepada suami sebagai pangestoh (berkah) yang merupakan bentuk pengabdian istri kepada sang suami.\n\nProses pewarnaan batik ini menggunakan gentong. Media pewarnaan ini dinilai dapat menghasilkan warna batik yang lebih cerah, karena ketika proses perendaman batik tidak boleh terkena paparan sinar matahari. Dari segi warna, karakteristik warna yang digunakan cenderung berani dan tegas, seperti warna merah yang melambangkan karakter masyarakat Madura yang kuat dan keras.\n\nSementara itu, corak dan motifnya menggambarkan kegiatan nelayan dan hewan-hewan yang dijumpai ketika pergi melaut, karena sebagian besar masyarakat Bangkalan bermata pencaharian sebagai nelayan.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_gentongan.jpg'),
(10, 'Batik Geblek Renteng', 'Yogyakarta', 'Batik Geblek Renteng, batik khas Kulon Progo, dikembangkan pada tahun 2012 untuk melestarikan budaya lokal dan meningkatkan perekonomian masyarakat. Motifnya terinspirasi dari Geblek Renteng, makanan khas Kulon Progo yang menyerupai angka delapan. Angka delapan dalam budaya Jawa melambangkan kemakmuran dan kesejahteraan. Geblek Renteng juga merupakan makanan yang populer di kalangan masyarakat Kulon Progo, sehingga motif ini melambangkan persatuan dan kesatuan masyarakat.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_geblekrenteng.jpg'),
(11, 'Batik Insang', 'Kalimantan Barat', 'Tenun corak insang adalah kain tenun tradisional yang dibuat oleh masyarakat Melayu di Kota Pontianak, Kalimantan Barat. Kain ini telah dikenal sejak masa Kesultanan Kadriah, yaitu pada masa pemerintahan Sultan Syarif Abdurrahman Al Qadrie pada tahun 1771 hingga sekarang.\n\nPada awalnya, tenun corak insang hanya digunakan oleh kaum bangsawan di Istana Kadriah Pontianak. Kain ini berfungsi sebagai penunjuk identitas status sosial bagi satu keluarga atau kelompok dalam kehidupan bermasyarakat maupun pertemuan antar kerajaan. Selain itu, kain ini juga berfungsi sebagai tolak ukur keterampilan anak pingit atau anak gadis pada masa lampau.\n\nCorak kain tenun ini terinspirasi dari bentuk insang ikan. Motif ini melambangkan kemakmuran dan kesejahteraan. Selain itu, motif insang juga melambangkan kesatuan dan persatuan masyarakat.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_insang.jpg'),
(12, 'Batik Kawung', 'Yogyakarta', 'Motif batik Kawung diperkirakan telah ada sejak abad ke-13. Motif ini awalnya muncul pada ukiran dinding di beberapa candi di Jawa, seperti Candi Prambanan. Motif batik Kawung adalah salah satu motif batik yang paling populer di Indonesia. Motif ini berbentuk bulatan yang tersusun secara geometris. Motif Kawung melambangkan kesempurnaan, kemurnian, dan kesucian.\n\nDalam kaitannya dengan kata suwung yang berarti kosong, motif Kawung menyimbolkan kekosongan nafsu dan hasrat duniawi. Kekosongan ini menjadikan seseorang netral, tidak berpihak, dan mengikuti arus kehidupan. Motif batik Kawung sering dikenakan oleh Semar, salah satu tokoh pewayangan Jawa. Semar adalah sosok yang bijaksana dan selalu memberikan nasihat kepada para Pandawa.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_kawung.jpg'),
(13, 'Batik Lasem', 'Jawa Tengah', 'Batik Lasem dari Kecamatan Lasem Kabupaten Rembang, Jawa Tengah misalnya, dari tiap motif yang tertuang di lembar kain merupakan hasil akulturasi budaya Tiongkok-Jawa. Tak heran jika melihat motif akan terlihat corak Jawa dan Tiongkok. Menariknya lagi, batik Lasem dibuat dengan cara tradisional.\n\nHal ini, karena dulunya para pengusaha batik Lasem adalah keturunan Tiongkok, dan dikonsumsi pula oleh kalangan Tiongkok itu sendiri. Namun, perkembangannya sekarang batik Lasem masih terus berkembang berinovasi.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_lasem.jpg'),
(14, 'Batik Megamendung', 'Jawa Barat', 'Motif Mega Mendung adalah salah satu jenis batik yang berasal dari daerah Cirebon, Jawa Barat. Berbeda dengan jenis batik lainnya, salah satu yang menjadi ciri khas dari batik motif Mega Mendung adalah ukiran awan dan langit yang digambarkan dalam batik.\n\nBatik Mega Mendung, menurut sejarah, berasal dari perpaduan budaya antara budaya Sunan Gunung Jati yang dulu ikut menyebarkan agama Islam di wilayah Cirebon dan bangsa Tionghoa yang dipimpin oleh Ratu Ong Tien. Pernikahan kedua tokoh ini menciptakan perpaduan budaya dari keduanya.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_megamendung.jpg'),
(15, 'Batik Pala', 'Maluku', 'Maluku merupakan salah satu daerah di Indonesia yang kaya akan rempah-rempah. Sehingga Maluku menjadi salah satu daerah penghasil rempah terbesar di Indonesia. Selain rempah-rempah, Maluku juga memiliki kekayaan budaya yang unik, yaitu batik. Batik Maluku memiliki beberapa motif, tetapi yang paling populer adalah motif pala, cengkih, dan parang-salawaku. Pala dan cengkih dipilih karena kedua hasil bumi ini merupakan komoditas utama Maluku.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_pala.jpg'),
(16, 'Batik Parang', 'Yogyakarta', 'Batik ini diciptakan oleh Panembahan Senopati, seorang bangsawan Kerajaan Mataram Islam. Kata Parang berasal dari kata Pereng yang berarti lereng. Maksudnya, bentuk motif batik parang itu berupa huruf S yang digambar secara berkaitan satu sama lain dan membentuk diagonal miring layaknya lereng gunung. Susunan bentuk S itu seolah menggambarkan ombak samudera yang tidak pernah habis hingga akhir zaman kelak.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_parang.jpg'),
(17, 'Batik Poleng', 'Bali', 'Batik poleng merupakan motif asli Bali yang menyerupai papan catur. Bagi masyarakat Bali, batik ini memiliki filosofi bhineda yiatu keseimbangan baik dan buruk.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_poleng.jpg'),
(18, 'Batik Sekar Jagad', 'Yogyakarta', 'Motif batik sekar jagad pertama kali muncul pada abad ke-19 dan diyakini berasal dari Bantul, tepatnya di Desa Pijenan. Pada awal keberadaannya, motif ini hanya digunakan pada pakaian tradisional kaum keraton atau keluarga kerajaan.\n\nSekar Jagad termasuk motif batik tradisional yang sarat akan nilai-nilai filosofi. Penting diketahui, Sekar Jagad diambil dari kata kar yang dalam Bahasa Belanda berarti peta, dan jagad yang berarti dunia dalam bahasa Jawa.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_sekarjagad.jpg'),
(19, 'Batik Tambal', 'Yogyakarta', 'Motif batik tambal memiliki arti tambal bermakna menambal atau memperbaiki hal-hal yang rusak. Dalam perjalanan hidupnya, manusia harus memperbaiki diri menuju kehidupan yang lebih baik, lahir maupun batin. Dahulu, kain batik bermotif tambal dipercaya bisa membantu kesembuhan orang yang sakit.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_tambal.jpg'),
(20, 'Batik Keraton', 'Yogyakarta', 'Batik keraton memiliki ciri khas tersendiri dengan paduan warna cokelat, hitam dan putih. Batik sebagai khazanah budaya Indonesia memiliki makna, filosofi dan harapan di dalamnya. Batik pedalaman atau sering disebut batik keraton yaitu batik yang berkembang di sekitar keraton dan mendapat pengaruh budaya keraton. Sering dikenakan untuk acara adat budaya, kaya akan makna, filosofi, spirit yang kental sekali dengan ajaran masyarakat Jawa.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_keraton.jpg'),
(21, 'Batik Pekalongan', 'Pekalongan, Jawa Tengah', 'Sebutan Kota Batik melekat pada Kota Pekalongan, bahkan pada tahun 1958 logo Kota Pekalongan ditetapkan dengan berbagai tambahan ornamen batik. Di Kota Pekalongan, kerajinan batik juga ditemukan di rumah dan perkampungan warga dan tak sedikit pula yang menjadikan batik ini sebagai mata pencaharian utama.  pada batik Pekalongan lebih banyak memainkan warna - warna yang lebih terang dan tidak terpaku pada 1 motif saja. Sehingga banyak kita jumpai batik Pekalongan yang memberikan motif makhluk hidup seperti tumbuh-tumbuhan dan hewan. Selain itu, pada beberapa motif batik Pekalongan terdapat pengaruh budaya negara lain.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_pekalongan.jpg'),
(22, 'Batik Priangan', 'Tasikmalaya, Jawa Barat', 'Batik Priyangan Tasikmalaya terkenal dengan ciri khasnya yang memiliki corak yang rapat, rapi, dan berkelas. Dominasi motif rumput dan tumbuh-tumbuhan menjadi identitas utama batik Priyangan.Secara garis besar, batik Tasikmalaya memiliki motif batik yang cenderung memberikan kesan semangat kesederhanaan, terbuka, dan pluralis serta memperlihatkan kesan imut selaras dengan citra umum wanita sunda.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_priangan.jpg'),
(23, 'Batik Sidoluhur', 'Yogyakarta dan Surakarta', 'Batik Sido Luhur disebut juga sebagai batik keraton yang dikembangkan di wilayah Yogyakarta dan Surakarta. Secara umum batik ini bermakna keluhuran, dalam artian orang Jawa dalam menjalani kehidupannya akan selalu mewujudkan keluhuran baik secara materi maupun non materi. Di keraton Surakarta motif batik Sido Luhur ini digunakan untuk temanten putri pada saat malam pengantin atau pernikahan. Dalam pandangan budaya Jawa telah dikatakan jika ketika memakai motif batik Sido Luhur ini, suatu saat nanti kehidupan rumah tangga mempelai akan mendapatkan kelancaran dan kemuliaan hidup.\n\nAda juga penggunaan motif batik Sido Luhur ini yang digunakan untuk acara mitoni atau upacara tujuh bulan kehamilan. Batik yang digunakan dengan latar berwarna putih, yang harapannya mampu memberikan kebahagiaan bagi pemakainya dengan tujuan supaya anak yang nanti dilahirkan dari rahim ibunya memiliki sifat budi pekerti luhur dan sopan santun.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_sidoluhur.jpg'),
(24, 'Batik Sidomukti', 'Surakarta, Jawa Tengah', 'Batik Sidomukti Solo (Surakarta) memiliki ciri khas yaitu corak yang digunakan dalam penggambaran lebih terkesan tradisional dengan konsep lekukan yang simetris.\n\nProses pembuatan nya pun harus mengalami beberapa fase dan aturan baku yang dijadikan pedoman, sehingga setiap motif dari batik Sidomukti memiliki filosofi dan makna sendiri-sendiri.\n\nSecara umum motif batik Sidomukti solo memiliki makna yaitu berusaha mendapatkan kebahagiaan secara lahir batin.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_sidomukti.jpg'),
(25, 'Batik Sogan', 'Yogyakarta dan Solo', 'Batik Sogan adalah salah satu jenis batik klasik. Nama Sogan diambil dari pohon soga yang digunakan dalam proses pembuatan batik ini. Umumnya batik Sogan Yogya berwarna coklat tua, hitam dan putih. Sementara batik Sogan Solo didominasi warna orange muda dan coklat. Makna batik Sogan tertuang dalam warna-warna yang digunakan. Berikut penjelasannya :\n\n- Hitam melambangkan nafsu atau keduniawian yang halal. \n\n- Merah melambangkan nafsu amarah.\n\n- Kuning melambangkan nafsu sufiyah.\n\n- Putih melambangkan nafsu mutmainah atau kebaikan. \n\n- Coklat melambangkan kekhidmatan dan kekhasan tradisi Jawa yang mengedepankan sisi batin.', 'https://storage.googleapis.com/batikpedia-src-407706/image/batik_sogan.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `produk`
--

DROP TABLE IF EXISTS `produk`;
CREATE TABLE `produk` (
  `id` int(11) NOT NULL,
  `nama_batik` varchar(50) NOT NULL,
  `url_produk` varchar(255) NOT NULL,
  `harga` varchar(10) NOT NULL,
  `gender` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Truncate table before insert `produk`
--

TRUNCATE TABLE `produk`;
--
-- Dumping data for table `produk`
--

INSERT INTO `produk` (`id`, `nama_batik`, `url_produk`, `harga`, `gender`) VALUES
(1, 'Bali', 'https://shp.ee/6vffhfk', '<100', 'Pria'),
(89, 'Dayak', 'https://shp.ee/t5dchvv', '100-300', 'Wanita'),
(300, 'Megamendung', 'https://shp.ee/sz23656', '>300', 'Pria');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `artikel_batik`
--
ALTER TABLE `artikel_batik`
  ADD UNIQUE KEY `id_artikel` (`id_artikel`);

--
-- Indexes for table `data_batik`
--
ALTER TABLE `data_batik`
  ADD UNIQUE KEY `id_batik` (`id_batik`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
